### ISSUE TITLE
Sound extension with different java versions in windows xp

### ISSUE THREAD

**Issue by turtlemaniac** [NetLogo/Sound-Extension#1] opened 2012-05-25 16:12 UTC
Sound extension in applet works, partially works(instruments sound incorrect, some don't do any sound) or doesn't(no sound at all) depending on netlogo version and java version in case the operating system is windows.

Using Netlogo 5.0.1:
Sound in applet works partially using Java Version 7 Update 4.
Sound in applet doesn't work using Java Version 6 Update 32.

I remember sound in applets worked with certain netlogo and java combinations, but can't recall the exact versions of both.

**Comment by brandesNW** [comment] 2023-09-13 14:19
Closing as Java is now bundled with NetLogo. Changes were made to the extension for Java 17. The issue is outdated

**Closed by brandesNW** 2023-09-13 14:19 UTC
